name: Terraform Init
description: Configures Terraform to run on the project

inputs:
  working_directory:
    required: true
  aws_access_key_id:
    required: true
  aws_secret_access_key:
    required: true
  aws_region:
    required: true
  aws_profile:
    required: true

outputs:
  terraform_workspace:
    value: ${{ steps.configure-workspace.outputs.terraform_workspace }}

runs:
  using: "composite"
  steps:
    - name: Install Terraform
      run: |
        echo "Installing Terraform"
        curl -L https://raw.githubusercontent.com/warrensbox/terraform-switcher/release/install.sh | sudo bash
        LOCAL_BIN="$HOME/.local/bin"
        grep -Eq "(:|^)$LOCAL_BIN(:|$)" <<< "$PATH" && mkdir -p "$LOCAL_BIN" || exit 1
        tfswitch --bin "$LOCAL_BIN/terraform"
      working-directory: ${{ inputs.working_directory }}
      shell: bash

    - name: Configure AWS credentials
      run: |
        echo "Configure AWS profile '${{ inputs.aws_profile }}'"
        aws configure set 'profile.${{ inputs.aws_profile }}.aws_access_key_id' '${{ inputs.aws_access_key_id }}'
        aws configure set 'profile.${{ inputs.aws_profile }}.aws_secret_access_key' '${{ inputs.aws_secret_access_key }}'
        aws configure set 'profile.${{ inputs.aws_profile }}.region' '${{ inputs.aws_region }}'
        aws configure set 'profile.${{ inputs.aws_profile }}.output' json
        echo 'AWS_PROFILE=${{ inputs.aws_profile }}' >> $GITHUB_ENV
      shell: bash

    - name: Initialize working directory
      run: terraform init -backend-config="../config/backend_config.tfvars"
      working-directory: ${{ inputs.working_directory }}
      shell: bash

    - name: Configure Terraform workspace
      id: configure-workspace
      run: |
        if [ "$(basename '${{ inputs.working_directory }}')" != "environment" ]; then
          TF_WORKSPACE="default"
        elif [ "$GITHUB_REF" == "refs/heads/main" ]; then
          TF_WORKSPACE="dev"
        else
          TF_WORKSPACE="$(: "${GITHUB_REF#'refs/tags/deployment/'}"; echo "${_%%/*}")"
        fi
        echo "Setting Terraform workspace to '$TF_WORKSPACE'"
        echo "::set-output name=terraform_workspace::$TF_WORKSPACE"
        echo "TF_WORKSPACE=$TF_WORKSPACE" >> $GITHUB_ENV
      shell: bash
