version: "3.8"

x-postgres-db: &postgres-db postgres
x-postgres-user: &postgres-user postgres
x-postgres-password: &postgres-password password

services:
  ingress:
    build: ingress
    ports:
      - "8000:80"
    restart: unless-stopped

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: *postgres-db
      POSTGRES_USER: *postgres-user
      POSTGRES_PASSWORD: *postgres-password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    environment:
      PORT: 3000
      PGHOST: postgres
      PGPORT: 5432
      PGDATABASE: *postgres-db
      PGUSER: *postgres-user
      PGPASSWORD: *postgres-password
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      - postgres

  frontend:
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - backend

volumes:
  pgdata:
