# Autogenerated by the s3_terraform_backend module, do not modify this file
region         = "us-west-2"
bucket         = "ecsstack-terraform-backend"
dynamodb_table = "ecsstack-terraform-lock"
profile        = "ecsstack"
