# Autogenerated by the s3_terraform_backend module, do not modify this file
region         = "us-west-2"
bucket         = "mystack-terraform-backend"
dynamodb_table = "TerraformLock"
profile        = "mystack"
