name: Basic Example - Test
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  fmt:
    name: Check Terraform formatting
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2

      - name: Terraform fmt
        uses: ./.github/actions/terraform-fmt
        with:
          working_directory: basic/terraform

  validate-global:
    name: Validate global Terraform configuration
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2

      - name: Terraform init
        uses: ./.github/actions/terraform-init
        with:
          working_directory: basic/terraform/global
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-west-2
          aws_profile: mystack

      - name: Validate Terraform dependency lock file
        run: |
          if git diff --name-only . | grep -q '.terraform.lock.hcl'; then
            echo 'Terraform dependency lock file has changed'
            exit 1
          else
            echo 'Terraform dependency lock file is up to date'
          fi
        working-directory: basic/terraform/global

      - name: Terraform validate
        uses: ./.github/actions/terraform-validate
        with:
          working_directory: basic/terraform/global

  validate-environment:
    name: Validate environment Terraform configuration
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2

      - name: Terraform init
        uses: ./.github/actions/terraform-init
        with:
          working_directory: basic/terraform/environment
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-west-2
          aws_profile: mystack

      - name: Validate Terraform dependency lock file
        run: |
          if git diff --name-only . | grep -q '.terraform.lock.hcl'; then
            echo 'Terraform dependency lock file has changed'
            exit 1
          else
            echo 'Terraform dependency lock file is up to date'
          fi
        working-directory: basic/terraform/environment

      - name: Terraform validate
        uses: ./.github/actions/terraform-validate
        with:
          working_directory: basic/terraform/environment
