name: EKS Example - Test
on:
  workflow_dispatch:
  # pull_request:
  # push:
  #   branches:
  #     - main

jobs:
  fmt:
    name: Check Terraform formatting
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2

      - name: Terraform fmt
        uses: Originate/github-actions/terraform-fmt@v1
        with:
          working_directory: examples/eks/terraform

  validate-global:
    name: Validate global Terraform configuration
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2

      - name: AWS configure
        uses: Originate/github-actions/aws-configure@v1
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-west-2
          aws_profile: eksstack

      - name: Terraform init
        uses: Originate/github-actions/terraform-init@v1
        with:
          working_directory: examples/eks/terraform/global

      - name: Validate Terraform dependency lock file
        run: |
          if git diff --name-only . | grep -q '.terraform.lock.hcl'; then
            echo 'Terraform dependency lock file has changed'
            exit 1
          else
            echo 'Terraform dependency lock file is up to date'
          fi
        working-directory: examples/eks/terraform/global

      - name: Terraform validate
        uses: Originate/github-actions/terraform-validate@v1
        with:
          working_directory: examples/eks/terraform/global

  validate-environment:
    name: Validate environment Terraform configuration
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2

      - name: AWS configure
        uses: Originate/github-actions/aws-configure@v1
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-west-2
          aws_profile: eksstack

      - name: Terraform init
        uses: Originate/github-actions/terraform-init@v1
        with:
          working_directory: examples/eks/terraform/environment

      - name: Validate Terraform dependency lock file
        run: |
          if git diff --name-only . | grep -q '.terraform.lock.hcl'; then
            echo 'Terraform dependency lock file has changed'
            exit 1
          else
            echo 'Terraform dependency lock file is up to date'
          fi
        working-directory: examples/eks/terraform/environment

      - name: Terraform validate
        uses: Originate/github-actions/terraform-validate@v1
        with:
          working_directory: examples/eks/terraform/environment
